language: php
php:
  - 5.3
  - 5.4
before_script:
  - wget https://github.com/nicolasff/phpredis/zipball/2.2.1
  - unzip 2.2.1
  - sh -c "cd nicolasff-phpredis-250e81b && phpize && ./configure && sudo make install"
  - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
script: cd ./tests && phpunit